### ISSUE TITLE
Crash when starting: File "/usr/local/bin/daphne", line 8, in <module>

### ISSUE THREAD

**Issue by Bixilon** [openwisp/docker-openwisp#157]
Hi there,
I updated to the newest version and not my openwisp is always crashing:

Here is a stack trace (taken with `docker logs` from the dashboard container):

```
2021-06-11 22:36:22,117 INFO Set uid to user 0 succeeded
2021-06-11 22:36:22,117 INFO Set uid to user 0 succeeded
2021-06-11 22:36:22,119 INFO supervisord started with pid 1
2021-06-11 22:36:22,119 INFO supervisord started with pid 1
2021-06-11 22:36:23,122 INFO spawned: 'daphne' with pid 11
2021-06-11 22:36:23,122 INFO spawned: 'daphne' with pid 11
2021-06-11 22:36:24,123 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-06-11 22:36:24,123 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/local/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/usr/local/lib/python3.7/site-packages/daphne/cli.py", line 191, in entrypoint
    cls().run(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/daphne/cli.py", line 252, in run
    application = import_by_path(args.application)
  File "/usr/local/lib/python3.7/site-packages/daphne/utils.py", line 12, in import_by_path
    target = importlib.import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./openwisp/asgi.py", line 11, in <module>
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./openwisp/settings.py", line 36, in <module>
    f'{HTTP_SCHEME}://{os.environ["API_DOMAIN"]}',
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'API_DOMAIN'
2021-06-11 22:36:24,212 INFO exited: daphne (exit status 1; not expected)
2021-06-11 22:36:24,212 INFO exited: daphne (exit status 1; not expected)
2021-06-11 22:36:25,217 INFO spawned: 'daphne' with pid 14
2021-06-11 22:36:25,217 INFO spawned: 'daphne' with pid 14
```

It looks like a environment variable called `API_DOMAIN` is missing. How to I set it in the container? I am starting it with `make start` like in the manual.

Thanks

**Comment by Bixilon** [comment]
Okay, after setting `API_DOMAIN` in `/opt/openwisp/docker-openwisp/.env` there is no crash anymore, but I still can't connect to it

**Comment by atb00ker** [comment]
Hi,

Yes recently the architecture was changed to convert `CONTROLLER_DOMAIN` & `TOPOLOGY_DOMAIN` to `API_DOMAIN`.
Now, we will have one container for UI (`DASHBOARD_DOMAIN`) and another one for api (`API_DOMAIN`).


Can you please share the logs of the api & nginx container? If there are no logs, please change:
```
DEBUG_MODE=True
DJANGO_LOG_LEVEL=DEBUG
```
then do `make stop` and `make start` again to see more logs. :smile:

**Comment by Bixilon** [comment]
Hi, thanks for the answer. I enabled debug mode, but I can't see an nginx container:
```
root@openwisp:/opt/openwisp/docker-openwisp# docker container list
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS         PORTS                                                           NAMES
f9c5e86303df   openwisp/openwisp-freeradius:latest   "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   0.0.0.0:1812-1813->1812-1813/udp, :::1812-1813->1812-1813/udp   docker-openwisp_freeradius_1
f6cbdcab452d   openwisp/openwisp-topology:latest     "bash init_command.sh"   2 minutes ago   Up 2 minutes   8003/tcp                                                        docker-openwisp_topology_1
a37ace60011a   openwisp/openwisp-controller:latest   "bash init_command.sh"   2 minutes ago   Up 2 minutes   8001/tcp                                                        docker-openwisp_controller_1
9bd9e57088bd   openwisp/openwisp-dashboard:latest    "bash init_command.sh"   2 minutes ago   Up 2 minutes   8000/tcp                                                        docker-openwisp_celerybeat_1
ec8fb0d585ac   openwisp/openwisp-websocket:latest    "supervisord --nodae…"   2 minutes ago   Up 2 minutes   8003/tcp                                                        docker-openwisp_websocket_1
6afcc4a2de03   openwisp/openwisp-dashboard:latest    "bash init_command.sh"   2 minutes ago   Up 2 minutes   8000/tcp                                                        docker-openwisp_celery_1
ec32de203997   openwisp/openwisp-radius:latest       "bash init_command.sh"   2 minutes ago   Up 2 minutes   8002/tcp                                                        docker-openwisp_radius_1
f7f59e95f57c   openwisp/openwisp-dashboard:latest    "bash init_command.sh"   2 minutes ago   Up 2 minutes   8000/tcp                                                        docker-openwisp_dashboard_1
436f4f935a60   openwisp/openwisp-openvpn:latest      "sh init_command.sh"     2 minutes ago   Up 2 minutes   1194/tcp, 0.0.0.0:1194->1194/udp, :::1194->1194/udp             docker-openwisp_openvpn_1
78993da52413   openwisp/openwisp-postfix:latest      "sh init_command.sh"     2 minutes ago   Up 2 minutes   25/tcp                                                          docker-openwisp_postfix_1
00b04304e311   redis:alpine                          "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   6379/tcp                                                        docker-openwisp_redis_1
e9de4bae4f7d   mdillon/postgis:11-alpine             "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   5432/tcp                                                        docker-openwisp_postgres_1
```

But here is the extract of `docker logs`:
```
root@openwisp:/opt/openwisp/docker-openwisp# docker logs 9bd9e57088bd
Waiting for database to become available...
Connection with database established.
Waiting for OpenWISP dashboard to become available...
Connection with OpenWISP dashboard established.
Waiting for redis to become available...
Connection with redis established.
celery beat v4.4.7 (cliffs) is starting.

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:47,815],process: 13, thread: 139882904282944
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:47,815],process: 13, thread: 139882904282944
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:48,443],process: 13, thread: 139882904282944
Using selector: EpollSelector

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:49,156],process: 13, thread: 139882904282944
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:49,156],process: 13, thread: 139882904282944
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[9bd9e57088bd] - DEBUG, time: [2021-06-12 03:38:49,156],process: 13, thread: 139882904282944
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
__    -    ... __   -        _
LocalTime -> 2021-06-12 03:38:49
Configuration ->
    . broker -> redis://redis:6379/1
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%DEBUG
    . maxinterval -> 5.00 minutes (300s)
[2021-06-12 03:38:49,594: DEBUG/MainProcess] Setting default socket timeout to 30
[2021-06-12 03:38:49,594: INFO/MainProcess] beat: Starting...
[2021-06-12 03:38:49,694: DEBUG/MainProcess] Current schedule:
<ScheduleEntry: notification-delete-tasks openwisp_notifications.tasks.delete_old_notifications(90) <crontab: 0 23 * * * (m/h/d/dM/MY)>
<ScheduleEntry: radius-periodic-tasks openwisp.tasks.radius_tasks() <crontab: 30 3 * * * (m/h/d/dM/MY)>
<ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
[2021-06-12 03:38:49,694: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
[2021-06-12 03:38:49,696: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
```

```
root@openwisp:/opt/openwisp/docker-openwisp# docker logs 6afcc4a2de03
Waiting for database to become available...
Connection with database established.
Waiting for OpenWISP dashboard to become available...
Connection with OpenWISP dashboard established.
Waiting for redis to become available...
Connection with redis established.

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:48,099],process: 10, thread: 140428163274560
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:48,099],process: 10, thread: 140428163274560
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:48,801],process: 10, thread: 140428163274560
Using selector: EpollSelector

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:49,541],process: 10, thread: 140428163274560
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:49,541],process: 10, thread: 140428163274560
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[6afcc4a2de03] - DEBUG, time: [2021-06-12 03:38:49,542],process: 10, thread: 140428163274560
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
/usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2021-06-12 03:38:49,996: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2021-06-12 03:38:49,998: DEBUG/MainProcess] | Worker: Building graph...
[2021-06-12 03:38:49,998: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Timer, Hub, Pool, Autoscaler, Beat, Consumer}
[2021-06-12 03:38:50,007: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2021-06-12 03:38:50,008: DEBUG/MainProcess] | Consumer: Building graph...
[2021-06-12 03:38:50,157: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Heart, Tasks, Control, Agent, event loop}
 
 -------------- celery@6afcc4a2de03 v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.8.14-050814-generic-x86_64-with-debian-10.8 2021-06-12 03:38:50
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         openwisp:0x7fb7f8e19150
- ** ---------- .> transport:   redis://redis:6379/1
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . openwisp.tasks.radius_tasks
  . openwisp.tasks.save_snapshot
  . openwisp.tasks.update_topology
  . openwisp_controller.config.tasks.create_vpn_dh
  . openwisp_controller.config.tasks.update_template_related_config_status
  . openwisp_controller.connection.tasks.update_config
  . openwisp_notifications.tasks.delete_ignore_object_notification
  . openwisp_notifications.tasks.delete_notification
  . openwisp_notifications.tasks.delete_obsolete_objects
  . openwisp_notifications.tasks.delete_old_notifications
  . openwisp_notifications.tasks.ns_organization_created
  . openwisp_notifications.tasks.ns_organization_user_added_or_updated
  . openwisp_notifications.tasks.ns_organization_user_deleted
  . openwisp_notifications.tasks.ns_register_unregister_notification_type
  . openwisp_notifications.tasks.ns_user_created
  . openwisp_radius.tasks.cleanup_stale_radacct
  . openwisp_radius.tasks.deactivate_expired_users
  . openwisp_radius.tasks.delete_old_postauth
  . openwisp_radius.tasks.delete_old_radacct
  . openwisp_radius.tasks.delete_old_users

[2021-06-12 03:38:50,163: DEBUG/MainProcess] | Worker: Starting Hub
[2021-06-12 03:38:50,163: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:50,163: DEBUG/MainProcess] | Worker: Starting Pool
[2021-06-12 03:38:50,213: DEBUG/ForkPoolWorker-1] Using selector: EpollSelector
[2021-06-12 03:38:50,280: DEBUG/ForkPoolWorker-2] Using selector: EpollSelector
[2021-06-12 03:38:50,344: DEBUG/ForkPoolWorker-3] Using selector: EpollSelector
[2021-06-12 03:38:50,403: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:50,403: DEBUG/MainProcess] | Worker: Starting Consumer
[2021-06-12 03:38:50,403: DEBUG/MainProcess] | Consumer: Starting Connection
[2021-06-12 03:38:50,407: DEBUG/ForkPoolWorker-4] Using selector: EpollSelector
[2021-06-12 03:38:50,413: INFO/MainProcess] Connected to redis://redis:6379/1
[2021-06-12 03:38:50,413: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:50,413: DEBUG/MainProcess] | Consumer: Starting Events
[2021-06-12 03:38:50,419: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:50,420: DEBUG/MainProcess] | Consumer: Starting Mingle
[2021-06-12 03:38:50,420: INFO/MainProcess] mingle: searching for neighbors
[2021-06-12 03:38:51,436: INFO/MainProcess] mingle: all alone
[2021-06-12 03:38:51,436: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:51,436: DEBUG/MainProcess] | Consumer: Starting Gossip
[2021-06-12 03:38:51,446: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:51,446: DEBUG/MainProcess] | Consumer: Starting Heart
[2021-06-12 03:38:51,451: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:51,451: DEBUG/MainProcess] | Consumer: Starting Tasks
[2021-06-12 03:38:51,468: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:51,469: DEBUG/MainProcess] | Consumer: Starting Control
[2021-06-12 03:38:51,477: DEBUG/MainProcess] ^-- substep ok
[2021-06-12 03:38:51,478: DEBUG/MainProcess] | Consumer: Starting event loop
[2021-06-12 03:38:51,478: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2021-06-12 03:38:51,480: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:206: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  leak, never use this setting in production environments!''')
[2021-06-12 03:38:51,480: INFO/MainProcess] celery@6afcc4a2de03 ready.
[2021-06-12 03:38:51,480: DEBUG/MainProcess] basic.qos: prefetch_count->4
[2021-06-12 03:38:51,486: INFO/MainProcess] Received task: openwisp_notifications.tasks.ns_register_unregister_notification_type[775466ab-08f2-47f3-89ad-37dc414cafc3]  
[2021-06-12 03:38:51,487: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fb7f8be7680> (args:('openwisp_notifications.tasks.ns_register_unregister_notification_type', '775466ab-08f2-47f3-89ad-37dc414cafc3', {'lang': 'py', 'task': 'openwisp_notifications.tasks.ns_register_unregister_notification_type', 'id': '775466ab-08f2-47f3-89ad-37dc414cafc3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '775466ab-08f2-47f3-89ad-37dc414cafc3', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen10@f7f59e95f57c', 'reply_to': 'abfe6ae4-e6c2-3094-b7c4-7a5269517671', 'correlation_id': '775466ab-08f2-47f3-89ad-37dc414cafc3', 'hostname': 'celery@6afcc4a2de03', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}, 'args': [], 'kwargs': {}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2021-06-12 03:38:51,488: DEBUG/MainProcess] Task accepted: openwisp_notifications.tasks.ns_register_unregister_notification_type[775466ab-08f2-47f3-89ad-37dc414cafc3] pid:28
[2021-06-12 03:38:51,539: INFO/ForkPoolWorker-2] Task openwisp_notifications.tasks.ns_register_unregister_notification_type[775466ab-08f2-47f3-89ad-37dc414cafc3] succeeded in 0.05057762889191508s: None
```

```
root@openwisp:/opt/openwisp/docker-openwisp# docker logs f7f59e95f57c
Waiting for database to become available...
Connection with database established.
Waiting for redis to become available...
Connection with redis established.

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:35,446],process: 10, thread: 140671373883200
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:35,446],process: 10, thread: 140671373883200
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:38,867],process: 10, thread: 140671373883200
Using selector: EpollSelector

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:39,546],process: 10, thread: 140671373883200
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:39,546],process: 10, thread: 140671373883200
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:39,547],process: 10, thread: 140671373883200
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:39,916],process: 10, thread: 140671373883200
Using selector: EpollSelector
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, config, connection, contenttypes, geo, openwisp_notifications, openwisp_radius, openwisp_users, pki, reversion, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:41,161],process: 27, thread: 139988068042560
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:41,161],process: 27, thread: 139988068042560
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:41,704],process: 27, thread: 139988068042560
Using selector: EpollSelector

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,234],process: 27, thread: 139988068042560
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,235],process: 27, thread: 139988068042560
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,235],process: 27, thread: 139988068042560
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,357],process: 27, thread: 139988068042560
Using selector: EpollSelector

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,959],process: 44, thread: 140347122800448
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:42,960],process: 44, thread: 140347122800448
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:43,479],process: 44, thread: 140347122800448
Using selector: EpollSelector

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,017],process: 44, thread: 140347122800448
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,017],process: 44, thread: 140347122800448
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,017],process: 44, thread: 140347122800448
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>

0 static files copied to '/opt/openwisp/static', 296 unmodified.

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,172],process: 44, thread: 140347122800448
Using selector: EpollSelector
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jun 12 03:38:44 2021] ***
compiled with version: 8.3.0 on 17 May 2021 13:48:33
os: Linux-5.8.14-050814-generic #202010070730 SMP Wed Oct 7 07:35:25 UTC 2020
nodename: f7f59e95f57c
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/openwisp
writing pidfile to /opt/openwisp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /opt/openwisp
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.9 (default, Feb  9 2021, 08:45:31)  [GCC 8.3.0]
Python main interpreter initialized at 0x555e38237140
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 274608 bytes (268 KB) for 4 cores
*** Operational MODE: preforking+threaded ***

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,764],process: 62, thread: 139850585315136
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:44,764],process: 62, thread: 139850585315136
Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:45,285],process: 62, thread: 139850585315136
Using selector: EpollSelector

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:45,846],process: 62, thread: 139850585315136
registered 'lmhash' handler: <class 'passlib.handlers.windows.lmhash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:45,846],process: 62, thread: 139850585315136
registered 'nthash' handler: <class 'passlib.handlers.windows.nthash'>

[f7f59e95f57c] - DEBUG, time: [2021-06-12 03:38:45,846],process: 62, thread: 139850585315136
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555e38237140 pid: 62 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 62)
spawned uWSGI worker 1 (pid: 79, cores: 2)
spawned uWSGI worker 2 (pid: 81, cores: 2)
[f7f59e95f57c] - pid: 79 - (-) {16 vars in 159 bytes} [Sat Jun 12 03:38:45 2021] GET / => generated 0 bytes in 273 msecs (HTTP/1.1 302) 7 headers in 200 bytes (1 switches on core 0)
[f7f59e95f57c] - pid: 79 - (-) {16 vars in 159 bytes} [Sat Jun 12 03:38:45 2021] GET / => generated 0 bytes in 273 msecs (HTTP/1.1 302) 7 headers in 200 bytes (1 switches on core 1)
[f7f59e95f57c] - pid: 79 - (-) {16 vars in 159 bytes} [Sat Jun 12 03:38:46 2021] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 302) 7 headers in 200 bytes (1 switches on core 0)
[f7f59e95f57c] - pid: 81 - (-) {16 vars in 159 bytes} [Sat Jun 12 03:38:45 2021] GET / => generated 0 bytes in 297 msecs (HTTP/1.1 302) 7 headers in 200 bytes (1 switches on core 1)
[f7f59e95f57c] - pid: 81 - (-) {16 vars in 159 bytes} [Sat Jun 12 03:38:45 2021] GET / => generated 0 bytes in 301 msecs (HTTP/1.1 302) 7 headers in 200 bytes (1 switches on core 0)
```





There are 3 containers with the dashboard. Are those the nginx logs or where/how can I find them?


Thanks 
Moritz

**Comment by atb00ker** [comment]
The fact that you don't see the nginx container explains why it's not working.
`make start` does start nginx container as well, not sure what happened on your machine.

Try:

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

If you don't have any data on your openwisp instance, please remove the database as well by using commands:
```
docker network rm $(docker network ls -q)
docker volume rm $(docker volume ls -q)
``` 

Then do 
```
make start
```

A fresh start should ensure the nginx container is there.

If this doesn't work, please let me know:
1. How are you installing docker-openwisp? What steps are you following?
2. Have you pulled the latest code from `openwisp/docker-openwisp` before trying to pull the latest images?
3. Have you made any modifications to the code?
4. Can you share the system information? Distro / version / docker version / docker-compose version etc? These details should help me reproduce the problem! 😄

**Comment by Bixilon** [comment]
Hi, thanks. I can't remove the volumes, there is a ton of data. The system has been in production use for a couple of months. I have the latest code and made no modifications to it.

But I found out: After running `make start` a `openwisp/openwisp-nginx:latest` shows up, but it pretty much crashes after 10 seconds with:
```root@openwisp:/opt/openwisp/docker-openwisp# docker logs 723764a57056
2021/06/12 23:31:38 [emerg] 40#40: host not found in upstream "api" in /etc/nginx/conf.d/api.https.conf:71
nginx: [emerg] host not found in upstream "api" in /etc/nginx/conf.d/api.https.conf:71
```

It's normal nginx behavior if it can't resolve a hostname. api can't be resolved and probably shouldn't? The domain in the `.env` file is `openwisp-api.xx.de`. It can be resolved on the host.


(Don't be afraid and that is definitely not the problem, the system was already up and running): 
A am running openwisp in a LXD container. The containers only purpose is running openwisp.  I am using kernel 5.8 on Ubuntu 20.04 (yah, ik, only 18.04 is supported). Running `Docker version 20.10.7, build f0df350`

Thanks for the help!

**Comment by atb00ker** [comment]
> The system has been in production use for a couple of months.

Thanks for informing this. Since docker-openwisp isn't officially released and ansible-openwisp2 is still the official installation method. Hence, I didn't think about backward compatibility but since you are already using it, I'll keep it in mind and at least post instructions to upgrade from alpha7 release onwards.

> (Don't be afraid and that is definitely not the problem, the system was already up and running

Okay, so is the issue solved? If hostname was not found my nginx, I am 99% certain just doing :
```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```
would have fixed it, deleting data isn't required for sure!

**Comment by Bixilon** [comment]
It is not solved yet, the "don't be afraid" was referred to LXD. 

I am not a fan of ansible, docker is far easier and kind of better.


How can I "resolve" the host?

**Comment by atb00ker** [comment]
I just noticed in your list of containers above that the api container is missing,
if you can join the chat room on 
Matrix: https://app.element.io/#/room/#openwisp_dockerize-openwisp:gitter.im
or
Gitter: https://gitter.im/openwisp/dockerize-openwisp

Then we can quickly debug and find the problem.

**Comment by Bixilon** [comment]
Looks like it is working:

 1. Backup `.env`
 2. Make git pull in `/opt/openwisp/docker-openwisp`
 3. restore and set `API_URL`
 4. start
