### ISSUE TITLE
[bug] dashboard unavailable

### ISSUE THREAD

**Issue by systemcrash** [openwisp/docker-openwisp#262]
Sorry folks, tried with `latest`, `edge`. Edge logs this loop:

```
Waiting for database to become available...
Connection with database established.
Waiting for redis to become available...
Connection with redis established.
Traceback (most recent call last):
  File "/opt/openwisp/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'import_export'
```

Came back to `latest` and finally got it up...
Very important to let users know that their `.env` file requires these for dashboard to start up 😄 
```
# uWSGI
UWSGI_PROCESSES=2
UWSGI_THREADS=2
UWSGI_LISTEN=100
```

**Comment by nemesisdesign** [comment]
Thanks for reporting, even if as our [docs indicate this repo is not ready for mass usage yet](https://openwisp.io/docs/user/quickstart.html#install-the-openwisp-server-application) your reports are surely going to help us improve it, so many thanks for taking the time to open these issues :pray:.

**Comment by nemesifier** [comment]
Should be fixed on latest master, please reopen if that's not the case.
