### ISSUE TITLE
[bug] Auto install fail

### ISSUE THREAD

**Issue by abplayzGH** [openwisp/docker-openwisp#299]
I tried to install on a Ubuntu 22.04 fresh install with the auto-install I got this error:

`
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
make: *** [Makefile:79: start] Error 1
make: Leaving directory '/opt/openwisp/docker-openwisp'
`

Also, how should I install OpenWisp? I tried the auto install, ansible, make file, and docker-compose and got none of them to work.

**Comment by nemesifier** [comment]
@abplayzGH At the moment I recommend deploying with ansible-openwisp2 on Debian 11.
Please use the [other support channels like general chat or mailing list](https://openwisp.org/support.html) if you have other questions that are not relevant to bug reports.

**Comment by nemesifier** [comment]
I haven't used this script much latelly, I think we need to add some automated tests for it or we'll never know whenever it breaks for some reason.

**Comment by sango74** [comment]
Good morning
Same error for me on a newly installed Debian 11.9

```
Starting Services...
Traceback (most recent call last):
File "/usr/local/bin/docker-compose", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/dist-packages/compose/cli/[main.py](http://main.py/)", line 81, in main
command_func()
File "/usr/local/lib/python3.9/dist-packages/compose/cli/[main.py](http://main.py/)", line 200, in perform_command
project = project_from_options('.', options)
File "/usr/local/lib/python3.9/dist-packages/compose/cli/[command.py](http://command.py/)", line 60, in project_from_options
return get_project(
File "/usr/local/lib/python3.9/dist-packages/compose/cli/[command.py](http://command.py/)", line 152, in get_project
client = get_client(

… escamotage de 1 ligne
client = docker_client(
File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_[client.py](http://client.py/)", line 124, in docker_client
kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
make: *** [Makefile:79 : start] Erreur 1
make : on quitte le répertoire « /opt/openwisp/docker-openwisp »
```

Thank

**Comment by MrCoolLV** [comment]
getting the same error

**Comment by nemesifier** [comment]
> Docker1 has made a [change](https://github.com/docker/docker-py/releases/tag/7.0.0) in v7.0.0 that breaks Docker Compose v1 written in Python (pip install docker-compose available as docker-compose). It has been deprecated and replaced by Docker Compose v2 implemented in Go which comes OOB as docker compose (sub-command).
> 
> Permanent fix: Switch to Docker Compose v2 (no extra installation required, read the [migration docs](https://docs.docker.com/compose/migrate) to fix compatibility issues). Docker Compose v2 switch is totally worth, btw; it is a near implementation.

Source: https://stackoverflow.com/a/77651191/462707

@pandafy we need to take this into account for the new release.

**Comment by nemesifier** [comment]
Update: I was able to get the latest master to work with Docker Compose v2, I updated the docs accordingly:
https://github.com/openwisp/docker-openwisp/pull/312.

**Comment by pandafy** [comment]
I found the following while working on this issue 

- `edge` version works: The script functions as expected when installing the edge version of the docker-openwisp application.
- `latest` version issues:
    - **Image Discrepancy**: The `latest` Docker image on GitLab seems to be more recent than the version associated with the `latest` tag on the GitHub repository.
    - **Missing Environment Variables**: The `latest` image on GitLab likely relies on environment variables that aren't included in the `latest` tag on GitHub. This mismatch could be causing the application to fail during installation with the script.

**Comment by pandafy** [comment]
i may have found the reason for mismatch for latest version https://github.com/openwisp/docker-openwisp/commit/206d229a96c629a4767ce131a689b3ba093d0914#r144385302
