### ISSUE TITLE
[bug] openwisp_controller.pki.models.MultipleObjectsReturned

### ISSUE THREAD

**Issue by atb00ker** [openwisp/docker-openwisp#97]
Recently, I've started seeing an issue with `load_init_script.py`:

```
dashboard_1   | Operations to perform:
dashboard_1   |   Apply all migrations: account, admin, auth, authtoken, config, connection, contenttypes, geo, openwisp_radius, openwisp_users, pki, reversion, sessions, sites, socialaccount, topology
dashboard_1   | Running migrations:
dashboard_1   |   No migrations to apply.
dashboard_1   | Traceback (most recent call last):
dashboard_1   |   File "load_init_data.py", line 139, in <module>
dashboard_1   |     os.environ['X509_NAME_CERT'])
dashboard_1   |   File "load_init_data.py", line 83, in create_default_cert
dashboard_1   |     return Cert.objects.get(name=x509NameCert)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
dashboard_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 403, in get
dashboard_1   |     (self.model._meta.object_name, num)
dashboard_1   | openwisp_controller.pki.models.MultipleObjectsReturned: get() returned more than one Cert -- it returned 2!
```

It shouldn't happen because to avoid creating multiple Certs, `if not Cert.objects.filter(name=x509NameCert).exists():` was added. But still somethow the Cert is created. Need to investigate.

**Comment by atb00ker** [comment]
Trying to delete the certificate causes:
```
dashboard_1   | 
dashboard_1   | [c38d4a6ff54c] - ERROR, time: [2020-01-29 17:01:10,730],process: 75, thread: 140320447543104
dashboard_1   | Internal Server Error: /admin/pki/cert/
dashboard_1   | Traceback (most recent call last):
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 163, in __get__
dashboard_1   |     rel_obj = self.field.get_cached_value(instance)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
dashboard_1   |     return instance._state.fields_cache[cache_name]
dashboard_1   | KeyError: 'cert'
dashboard_1   | 
dashboard_1   | During handling of the above exception, another exception occurred:
dashboard_1   | 
dashboard_1   | Traceback (most recent call last):
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
dashboard_1   |     response = get_response(request)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
dashboard_1   |     response = self.process_exception_by_middleware(e, request)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
dashboard_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
dashboard_1   |     return self.admin_site.admin_view(view)(*args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
dashboard_1   |     response = view_func(request, *args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
dashboard_1   |     response = view_func(request, *args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
dashboard_1   |     return view(request, *args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/reversion/admin.py", line 236, in changelist_view
dashboard_1   |     return super(VersionAdmin, self).changelist_view(request, context)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
dashboard_1   |     return bound_method(*args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
dashboard_1   |     response = view_func(request, *args, **kwargs)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1727, in changelist_view
dashboard_1   |     response = self.response_action(request, queryset=cl.get_queryset(request))
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1411, in response_action
dashboard_1   |     response = func(self, request, queryset)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/actions.py", line 40, in delete_selected
dashboard_1   |     modeladmin.delete_queryset(request, queryset)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1104, in delete_queryset
dashboard_1   |     queryset.delete()
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 660, in delete
dashboard_1   |     deleted, _rows_count = collector.delete()
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 306, in delete
dashboard_1   |     sender=model, instance=obj, using=self.using
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
dashboard_1   |     for receiver in self._live_receivers(sender)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
dashboard_1   |     for receiver in self._live_receivers(sender)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django_netjsonconfig/base/vpn.py", line 225, in post_delete
dashboard_1   |     instance.cert.delete()
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 177, in __get__
dashboard_1   |     rel_obj = self.get_object(instance)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 297, in get_object
dashboard_1   |     return super().get_object(instance)
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 144, in get_object
dashboard_1   |     return qs.get(self.field.get_reverse_related_filter(instance))
dashboard_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
dashboard_1   |     self.model._meta.object_name
dashboard_1   | openwisp_controller.pki.models.Cert.DoesNotExist: Cert matching query does not exist.
dashboard_1   | [c38d4a6ff54c] - pid: 75 172.18.0.1 (-) {56 vars in 1456 bytes} [Wed Jan 29 17:01:10 2020] POST /admin/pki/cert/ => generated 27 bytes in 97 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)
```

**Comment by atb00ker** [comment]
Most likely this is related to : https://github.com/openwisp/django-netjsonconfig/issues/130

**Comment by atb00ker** [comment]
I haven't seen this in a long while!
